/**
 * Linewatch — household outbound watch
 * Copyright (c) 2026 Chris Decker
 */
import type { Destination, Device } from "./types";

export type { Destination };

export const HOUSEHOLD: Device[] = [
  {
    id: "dev-riley-phone",
    name: "Riley's iPhone",
    owner: "Riley",
    role: "child",
    ip: "192.168.1.24",
    mac: "A4:83:E7:2C:91:04",
    kind: "phone",
    blocked: false,
    lastSeen: 0,
  },
  {
    id: "dev-sam-ipad",
    name: "Sam's iPad",
    owner: "Sam",
    role: "child",
    ip: "192.168.1.31",
    mac: "F0:18:98:6A:22:B1",
    kind: "tablet",
    blocked: false,
    lastSeen: 0,
  },
  {
    id: "dev-jordan-mac",
    name: "Jordan's MacBook",
    owner: "Jordan",
    role: "parent",
    ip: "192.168.1.12",
    mac: "3C:22:FB:11:08:C2",
    kind: "laptop",
    blocked: false,
    lastSeen: 0,
  },
  {
    id: "dev-avery-phone",
    name: "Avery's iPhone",
    owner: "Avery",
    role: "parent",
    ip: "192.168.1.18",
    mac: "D8:8F:76:40:AA:19",
    kind: "phone",
    blocked: false,
    lastSeen: 0,
  },
  {
    id: "dev-appletv",
    name: "Living Room Apple TV",
    owner: "House",
    role: "shared",
    ip: "192.168.1.40",
    mac: "90:72:40:CE:33:01",
    kind: "tv",
    blocked: false,
    lastSeen: 0,
  },
  {
    id: "dev-xbox",
    name: "Xbox Series",
    owner: "Sam",
    role: "child",
    ip: "192.168.1.55",
    mac: "7C:1E:52:09:B4:77",
    kind: "console",
    blocked: false,
    lastSeen: 0,
  },
  {
    id: "dev-ring",
    name: "Front Door Camera",
    owner: "House",
    role: "iot",
    ip: "192.168.1.71",
    mac: "10:AE:60:1D:44:2E",
    kind: "iot",
    blocked: false,
    lastSeen: 0,
  },
  {
    id: "dev-echo",
    name: "Kitchen Echo",
    owner: "House",
    role: "iot",
    ip: "192.168.1.74",
    mac: "FC:65:DE:08:91:AA",
    kind: "iot",
    blocked: false,
    lastSeen: 0,
  },
  {
    id: "dev-tile",
    name: "Riley's Tile",
    owner: "Riley",
    role: "iot",
    ip: "192.168.1.88",
    mac: "C0:97:27:4B:11:09",
    kind: "iot",
    blocked: false,
    lastSeen: 0,
  },
];

export const DESTINATIONS: Destination[] = [
  // Adult hosts Chris Decker classifies for household alerts (suffix match, no page body).
  { host: "pornhub.com", category: "adult", label: "Pornhub" },
  { host: "xvideos.com", category: "adult", label: "XVideos" },
  { host: "xnxx.com", category: "adult", label: "XNXX" },
  { host: "xhamster.com", category: "adult", label: "xHamster" },
  { host: "onlyfans.com", category: "adult", label: "OnlyFans" },
  { host: "chaturbate.com", category: "adult", label: "Chaturbate" },
  { host: "spankbang.com", category: "adult", label: "SpankBang" },
  { host: "redtube.com", category: "adult", label: "RedTube" },
  { host: "youporn.com", category: "adult", label: "YouPorn" },
  { host: "nhentai.net", category: "adult", label: "nhentai" },
  { host: "rule34.xxx", category: "adult", label: "Rule34" },
  { host: "pornhd.com", category: "adult", label: "PornHD" },
  { host: "brazzers.com", category: "adult", label: "Brazzers" },
  { host: "xhamsterlive.com", category: "adult", label: "xHamster Live" },
  { host: "instagram.com", category: "social", label: "Instagram" },
  { host: "cdninstagram.com", category: "social", label: "Instagram CDN" },
  { host: "tiktok.com", category: "social", label: "TikTok" },
  { host: "tiktokv.com", category: "social", label: "TikTok" },
  { host: "snapchat.com", category: "social", label: "Snapchat" },
  { host: "snap-dev.net", category: "social", label: "Snapchat" },
  { host: "discord.com", category: "social", label: "Discord" },
  { host: "discord.gg", category: "social", label: "Discord" },
  { host: "reddit.com", category: "social", label: "Reddit" },
  { host: "redd.it", category: "social", label: "Reddit" },
  { host: "twitter.com", category: "social", label: "X" },
  { host: "x.com", category: "social", label: "X" },
  { host: "facebook.com", category: "social", label: "Facebook" },
  { host: "fbcdn.net", category: "social", label: "Facebook CDN" },
  { host: "threads.net", category: "social", label: "Threads" },
  { host: "xboxlive.com", category: "gaming", label: "Xbox Live" },
  { host: "xbox.com", category: "gaming", label: "Xbox" },
  { host: "playstation.com", category: "gaming", label: "PlayStation" },
  { host: "steampowered.com", category: "gaming", label: "Steam" },
  { host: "steamcommunity.com", category: "gaming", label: "Steam" },
  { host: "epicgames.com", category: "gaming", label: "Epic Games" },
  { host: "roblox.com", category: "gaming", label: "Roblox" },
  { host: "minecraft.net", category: "gaming", label: "Minecraft" },
  { host: "twitch.tv", category: "gaming", label: "Twitch" },
  { host: "riotgames.com", category: "gaming", label: "Riot" },
  { host: "ea.com", category: "gaming", label: "EA" },
  { host: "activision.com", category: "gaming", label: "Activision" },
  { host: "netflix.com", category: "streaming", label: "Netflix" },
  { host: "nflxvideo.net", category: "streaming", label: "Netflix CDN" },
  { host: "youtube.com", category: "streaming", label: "YouTube" },
  { host: "googlevideo.com", category: "streaming", label: "YouTube CDN" },
  { host: "ytimg.com", category: "streaming", label: "YouTube" },
  { host: "disneyplus.com", category: "streaming", label: "Disney+" },
  { host: "hulu.com", category: "streaming", label: "Hulu" },
  { host: "spotify.com", category: "streaming", label: "Spotify" },
  { host: "scdn.co", category: "streaming", label: "Spotify CDN" },
  { host: "max.com", category: "streaming", label: "Max" },
  { host: "primevideo.com", category: "streaming", label: "Prime Video", path: "amazon" },
  { host: "google.com", category: "search", label: "Google" },
  { host: "bing.com", category: "search", label: "Bing" },
  { host: "duckduckgo.com", category: "search", label: "DuckDuckGo" },
  { host: "yahoo.com", category: "search", label: "Yahoo" },
  { host: "amazon.com", category: "shopping", label: "Amazon", path: "amazon" },
  { host: "amazon-adsystem.com", category: "ads", label: "Amazon Ads", path: "amazon" },
  { host: "ebay.com", category: "shopping", label: "eBay" },
  { host: "shopify.com", category: "shopping", label: "Shopify" },
  { host: "walmart.com", category: "shopping", label: "Walmart" },
  { host: "target.com", category: "shopping", label: "Target" },
  { host: "etsy.com", category: "shopping", label: "Etsy" },
  { host: "wikipedia.org", category: "education", label: "Wikipedia" },
  { host: "khanacademy.org", category: "education", label: "Khan Academy" },
  { host: "schoology.com", category: "education", label: "Schoology" },
  { host: "canvas.net", category: "education", label: "Canvas" },
  { host: "duolingo.com", category: "education", label: "Duolingo" },
  { host: "nytimes.com", category: "news", label: "NYTimes" },
  { host: "cnn.com", category: "news", label: "CNN" },
  { host: "bbc.com", category: "news", label: "BBC" },
  { host: "washingtonpost.com", category: "news", label: "Washington Post" },
  { host: "icloud.com", category: "messaging", label: "iCloud" },
  { host: "whatsapp.com", category: "messaging", label: "WhatsApp" },
  { host: "telegram.org", category: "messaging", label: "Telegram" },
  { host: "signal.org", category: "messaging", label: "Signal" },
  { host: "messenger.com", category: "messaging", label: "Messenger" },
  { host: "doubleclick.net", category: "ads", label: "DoubleClick" },
  { host: "googlesyndication.com", category: "ads", label: "AdSense" },
  { host: "googleadservices.com", category: "ads", label: "Google Ads" },
  { host: "scorecardresearch.com", category: "ads", label: "Scorecard" },
  { host: "advertising.com", category: "ads", label: "Advertising.com" },
  { host: "adnxs.com", category: "ads", label: "Xandr" },
  { host: "facebook.net", category: "ads", label: "Meta Pixel" },
  { host: "apple.com", category: "system", label: "Apple" },
  { host: "icloud-content.com", category: "cloud", label: "iCloud Content" },
  { host: "mzstatic.com", category: "system", label: "Apple Static" },
  { host: "googleapis.com", category: "cloud", label: "Google APIs" },
  { host: "gstatic.com", category: "cloud", label: "Google Static" },
  { host: "googleusercontent.com", category: "cloud", label: "Google User Content" },
  { host: "cloudflare.com", category: "cloud", label: "Cloudflare" },
  { host: "cloudfront.net", category: "cloud", label: "CloudFront" },
  { host: "akamaiedge.net", category: "cloud", label: "Akamai" },
  { host: "microsoft.com", category: "system", label: "Microsoft" },
  { host: "office.com", category: "cloud", label: "Microsoft 365" },
  { host: "live.com", category: "system", label: "Microsoft Live" },
  { host: "windowsupdate.com", category: "system", label: "Windows Update" },
  { host: "amazonaws.com", category: "cloud", label: "AWS", path: "amazon" },
  { host: "fastly.net", category: "cloud", label: "Fastly" },
  { host: "github.com", category: "cloud", label: "GitHub" },
  { host: "dropbox.com", category: "cloud", label: "Dropbox" },

  { host: "dns.google", category: "vpn", label: "Google DNS (DoH)" },
  { host: "cloudflare-dns.com", category: "vpn", label: "Cloudflare DNS" },
  { host: "dns.quad9.net", category: "vpn", label: "Quad9 DNS" },
  { host: "mozilla.cloudflare-dns.com", category: "vpn", label: "Firefox DoH" },
  { host: "nordvpn.com", category: "vpn", label: "NordVPN" },
  { host: "expressvpn.com", category: "vpn", label: "ExpressVPN" },
  { host: "protonvpn.com", category: "vpn", label: "Proton VPN" },
  { host: "surfshark.com", category: "vpn", label: "Surfshark" },
  { host: "mullvad.net", category: "vpn", label: "Mullvad" },
  { host: "windscribe.com", category: "vpn", label: "Windscribe" },
  { host: "privateinternetaccess.com", category: "vpn", label: "PIA" },
  { host: "mask.icloud.com", category: "vpn", label: "iCloud Private Relay" },
  { host: "mask-h2.icloud.com", category: "vpn", label: "iCloud Private Relay" },
  { host: "one.one.one.one", category: "vpn", label: "Cloudflare 1.1.1.1" },
  { host: "dns.nextdns.io", category: "vpn", label: "NextDNS" },
  { host: "dns.adguard.com", category: "vpn", label: "AdGuard DNS" },

  { host: "sidewalk.amazonaws.com", category: "cloud", label: "Amazon Sidewalk", path: "sidewalk" },
  { host: "sidewalk.amazon.com", category: "cloud", label: "Amazon Sidewalk", path: "sidewalk" },
  { host: "ring.com", category: "cloud", label: "Ring", path: "sidewalk" },
  { host: "wwn.ring.com", category: "cloud", label: "Ring WWN", path: "sidewalk" },
  { host: "alexa.amazon.com", category: "cloud", label: "Alexa", path: "sidewalk" },
  { host: "avs-alexa-12-na.amazon.com", category: "cloud", label: "Alexa Voice", path: "sidewalk" },
  { host: "fireos-static.amazon.com", category: "system", label: "Fire OS", path: "amazon" },
  { host: "device-metrics-us.amazon.com", category: "cloud", label: "Amazon device metrics", path: "amazon" },
  { host: "prod.unagi.amazon.com", category: "cloud", label: "Amazon Unagi", path: "amazon" },
  { host: "tile-api.com", category: "cloud", label: "Tile", path: "sidewalk" },
  { host: "theneitherworld.com", category: "cloud", label: "Tile locate", path: "sidewalk" },

  {
    host: "location.apple.com",
    category: "system",
    label: "Apple Location",
    locationHint: "Device GPS / Wi-Fi location sent to Apple",
  },
  {
    host: "gs-loc.apple.com",
    category: "system",
    label: "Apple GS-Loc",
    locationHint: "Crowdsourced Wi-Fi location lookup",
  },
  {
    host: "weatherkit.apple.com",
    category: "system",
    label: "WeatherKit",
    locationHint: "Local weather — implies a lat/long from the device",
  },
  {
    host: "maps.apple.com",
    category: "search",
    label: "Apple Maps",
    locationHint: "Maps session — typically includes a coordinate",
  },
  {
    host: "maps.googleapis.com",
    category: "search",
    label: "Google Maps API",
    locationHint: "Maps / Places — typically includes a coordinate",
  },
  {
    host: "www.google.com",
    category: "search",
    label: "Google",
  },
  {
    host: "weather.com",
    category: "news",
    label: "Weather.com",
    locationHint: "Forecast for a place — implies a location",
  },
  {
    host: "api.openweathermap.org",
    category: "cloud",
    label: "OpenWeather",
    locationHint: "Weather API keyed to a coordinate or ZIP",
  },
  {
    host: "waze.com",
    category: "search",
    label: "Waze",
    locationHint: "Live navigation — GPS in flight",
  },
  {
    host: "hereapi.com",
    category: "cloud",
    label: "HERE Maps",
    locationHint: "Location platform API",
  },
];

export const DEST_BY_HOST = new Map(DESTINATIONS.map((d) => [d.host, d]));
